version: 2.1

executors:
  rust-executor:
    docker:
      - image: rust:latest

jobs:
  build:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: build
          command: cargo build --verbose;
      - run:
          name: build --features stdweb
          command: cargo build --verbose --features "stdweb";
      - run:
          name: build --features wasm-bindgen
          command: cargo build --verbose --features "wasm-bindgen";
      - run:
          name: build --features now
          command: cargo build --verbose --features now;
      - run:
          name: build --features now stdweb
          command: cargo build --verbose --features "now stdweb";
      - run:
          name: build --features now wasm-bindgen
          command: cargo build --verbose --features "now wasm-bindgen";